config/routes.rb
Mp3App::Application.routes.draw do
  resources  :audios
  root :to => 'audios#index'

end

app/models/audio.rb
require "mp3info"
class Audio < ActiveRecord::Base
  attr_accessible :album, :artist, :audio_content_type, :audio_name, :audio_size, :audio_updated_at, :title, :track, :tracknum,:audio

  has_attached_file :audio,
  :url => "public/attachments/:id/:filename",
  :path => "public/attachments/:id/:filename"
  validates_attachment_content_type :audio, content_type: [ 'audio/mpeg', 'audio/x-mpeg' ], message: "has to be in MP3 format"

  before_save :extract_audio_details


# Retrieves metadata for MP3s
def extract_audio_details
   path = audio.queued_for_write[:original].path
  open_opts = { :encoding => 'utf-8' }
  Mp3Info.open(path, open_opts) do |mp3|
	  self.title = mp3.tag.title 
	  self.album = mp3.tag.album
	  self.artist = mp3.tag.artist
	  self.track = mp3.tag.tracknum
  end
end

# Search MP3s by title,album and artist
def self.search(search)
  where('title LIKE :search_key OR artist LIKE :search_key OR album like :search_key ',{search_key: "%#{search}%"})
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  def index
    @audios = params[:search] ? Audio.search(params[:search]) : Audio.all
  end
  
  def new
   @audio = Audio.new
  end

  def create
   @audio =  Audio.new(params[:audio])  
   if @audio.save
    redirect_to audios_path,notice: "File uploaded successfully"
   else
     render "new"
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/views/audios/create.html.erb
<h1>Audios#create</h1>
<p>Find me in app/views/audios/create.html.erb</p>

app/views/audios/destroy.html.erb
<h1>Audios#destroy</h1>
<p>Find me in app/views/audios/destroy.html.erb</p>

app/views/audios/index.html.erb
<%= link_to "Audios", audios_path,class: "link" %>
<%= link_to "Add Mp3", new_audio_path,class: "link" %>
<%= form_tag audios_path, :method => 'get' ,class: "searchform" do  %>
   <%= text_field_tag :search, params[:search],class: "searchfield",placeholder: "Search by Album, Artist, Title" %>
    <%= submit_tag "Search",class: "searchbutton" %>
<% end %>

<% if @audios.any? %>
  <div class="CSSTableGenerator" >
    <table >
      <tr>
        <td>Album</td>
        <td>Artist</td>
        <td >Title</td>
        <td>Track No</td>
      </tr>
      <%@audios.each do |audio|%>			
        <tr>
          <td><%= audio.album%></td>
          <td><%= audio.artist%></td>
          <td><%= audio.title%></td>
          <td><%= audio.track%></td>
        </tr>
      <%end%>
    </table>
  </div>
<%else%>
<div class="empty-list">
  <span>Oops! Audio list is empty</span>
</div>
<%end%>

app/views/audios/new.html.erb
<%= link_to "Back to Audios", audios_path,class: "link" %>

<div style="margin: -20px 100px;;">
  <%= form_for @audio, html: {multipart: true} do |form| %>
<% if @audio.errors.any? %>
    <div class="error">
      <ul>
        <% @audio.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.file_field :audio %>
  <%= form.submit%>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mp3App</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg.html_safe, :class => name %>
    <% end %>
    <%= yield %>

  </body>
</html>